-- Matchmake owner-only administration and live activity logging.
-- Apply after the core schema and scoped RLS policy files.

create schema if not exists private;
revoke all on schema private from public;
grant usage on schema private to authenticated;

create table if not exists private.owner_accounts (
  user_id uuid primary key references auth.users(id) on delete cascade,
  label text not null default 'Owner',
  created_at timestamptz not null default now()
);

alter table private.owner_accounts enable row level security;
revoke all on table private.owner_accounts from public, anon, authenticated;

create or replace function private.is_matchmake_owner()
returns boolean
language sql
stable
security definer
set search_path = private, auth, pg_temp
as $$
  select exists (
    select 1
    from private.owner_accounts owner_account
    where owner_account.user_id = (select auth.uid())
  )
$$;

revoke all on function private.is_matchmake_owner() from public;
grant execute on function private.is_matchmake_owner() to authenticated;

create or replace function public.is_matchmake_owner()
returns boolean
language sql
stable
security invoker
set search_path = private, public, pg_temp
as $$
  select private.is_matchmake_owner()
$$;

revoke all on function public.is_matchmake_owner() from public, anon;
grant execute on function public.is_matchmake_owner() to authenticated;

create table if not exists public.admin_activity_logs (
  id bigint generated by default as identity primary key,
  actor_user_id uuid references auth.users(id) on delete set null,
  entity_type text not null,
  entity_id uuid,
  action text not null,
  target_label text not null,
  status text not null default 'success'
    check (status in ('success', 'pending', 'failed', 'open')),
  details text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists admin_activity_logs_created_at_idx
  on public.admin_activity_logs(created_at desc);
create index if not exists admin_activity_logs_entity_idx
  on public.admin_activity_logs(entity_type, entity_id, created_at desc);
create index if not exists admin_activity_logs_actor_idx
  on public.admin_activity_logs(actor_user_id, created_at desc);

alter table public.admin_activity_logs enable row level security;
revoke all on table public.admin_activity_logs from public, anon, authenticated;
grant select, insert on table public.admin_activity_logs to authenticated;
grant usage on sequence public.admin_activity_logs_id_seq to authenticated;

drop policy if exists "Matchmake owners can read activity logs" on public.admin_activity_logs;
create policy "Matchmake owners can read activity logs"
  on public.admin_activity_logs
  for select
  to authenticated
  using ((select private.is_matchmake_owner()));

drop policy if exists "Authenticated users can insert launch analytics events" on public.admin_activity_logs;
create policy "Authenticated users can insert launch analytics events"
  on public.admin_activity_logs
  for insert
  to authenticated
  with check (
    actor_user_id = (select auth.uid())
    and entity_type = 'analytics'
    and action in ('signup_completed', 'scrim_posted', 'extraction_completed', 'extraction_failed')
    and status in ('success', 'pending', 'failed', 'open')
    and jsonb_typeof(metadata) = 'object'
  );

create or replace function private.capture_matchmake_activity()
returns trigger
language plpgsql
security definer
set search_path = public, private, auth, pg_temp
as $$
declare
  row_data jsonb;
  old_data jsonb;
  activity_actor uuid;
  activity_action text;
  activity_target text;
  activity_status text := 'success';
  activity_details text;
begin
  row_data := case when tg_op = 'DELETE' then to_jsonb(old) else to_jsonb(new) end;
  old_data := case when tg_op = 'UPDATE' then to_jsonb(old) else '{}'::jsonb end;
  activity_actor := (select auth.uid());
  activity_action := lower(tg_op);

  if tg_table_name = 'users' then
    activity_target := coalesce(row_data ->> 'display_name', row_data ->> 'email', 'User');
    activity_action := case tg_op when 'INSERT' then 'created user' when 'UPDATE' then 'updated user' else 'removed user' end;
    activity_details := coalesce(row_data ->> 'account_type', 'Account');
  elsif tg_table_name = 'organizations' then
    activity_target := coalesce(row_data ->> 'name', 'Organization');
    activity_action := case tg_op when 'INSERT' then 'created organization' when 'UPDATE' then 'updated organization' else 'removed organization' end;
    if tg_op = 'UPDATE' and (old_data ->> 'verified_flag') is distinct from (row_data ->> 'verified_flag') then
      activity_details := case when (row_data ->> 'verified_flag')::boolean then 'Organization verified' else 'Verification removed' end;
    else
      activity_details := coalesce(row_data ->> 'region', row_data ->> 'type', 'Organization record');
    end if;
  elsif tg_table_name = 'teams' then
    activity_target := coalesce(row_data ->> 'name', 'Team');
    activity_action := case tg_op when 'INSERT' then 'created team' when 'UPDATE' then 'updated roster' else 'removed team' end;
    activity_details := coalesce(row_data ->> 'game_title', 'Team record');
  elsif tg_table_name = 'scrim_requests' then
    activity_target := coalesce(row_data ->> 'game_title', 'Scrim') || ' scrim';
    activity_action := case tg_op when 'INSERT' then 'created scrim' when 'UPDATE' then 'updated scrim' else 'removed scrim' end;
    if tg_op = 'UPDATE' and (old_data ->> 'status') is distinct from (row_data ->> 'status') then
      activity_details := coalesce(old_data ->> 'status', 'unknown') || ' to ' || coalesce(row_data ->> 'status', 'unknown');
    else
      activity_details := 'Status: ' || coalesce(row_data ->> 'status', 'unknown');
    end if;
    activity_status := case
      when row_data ->> 'status' in ('pending', 'matched', 'accepted') then 'pending'
      when row_data ->> 'status' in ('declined', 'cancelled', 'expired') then 'open'
      else 'success'
    end;
  elsif tg_table_name = 'scrim_messages' then
    activity_target := coalesce(row_data ->> 'sender_display_name', 'Participant') || ' in scrim chat';
    activity_action := case tg_op when 'INSERT' then 'sent message' when 'UPDATE' then 'updated message' else 'removed message' end;
    activity_details := 'Conversation activity';
  elsif tg_table_name = 'team_match_reviews' then
    activity_actor := coalesce(activity_actor, nullif(row_data ->> 'created_by', '')::uuid);
    activity_target := coalesce(row_data ->> 'game_title', 'Match') || ' review';
    activity_action := case tg_op when 'INSERT' then 'submitted review' when 'UPDATE' then 'updated review' else 'removed review' end;
    activity_details := case
      when coalesce((row_data ->> 'manual_edit_required')::boolean, false) then 'Manual review required'
      else coalesce(row_data ->> 'match_result', row_data ->> 'parser_status', 'Review saved')
    end;
    activity_status := case
      when coalesce((row_data ->> 'manual_edit_required')::boolean, false) then 'pending'
      else 'success'
    end;
  else
    return coalesce(new, old);
  end if;

  insert into public.admin_activity_logs (
    actor_user_id,
    entity_type,
    entity_id,
    action,
    target_label,
    status,
    details,
    metadata
  ) values (
    activity_actor,
    tg_table_name,
    nullif(row_data ->> 'id', '')::uuid,
    activity_action,
    activity_target,
    activity_status,
    activity_details,
    jsonb_build_object('operation', tg_op)
  );

  return coalesce(new, old);
end
$$;

revoke all on function private.capture_matchmake_activity() from public, anon, authenticated;

create or replace function public.track_matchmake_analytics_event(
  event_name text,
  event_status text default 'success',
  target_label text default 'Launch analytics',
  entity_id uuid default null,
  event_details text default null,
  event_metadata jsonb default '{}'::jsonb
)
returns void
language plpgsql
security invoker
set search_path = public, private, auth, pg_temp
as $$
declare
  normalized_event text := lower(btrim(coalesce(event_name, '')));
  normalized_status text := lower(btrim(coalesce(event_status, 'success')));
  safe_metadata jsonb := '{}'::jsonb;
begin
  if (select auth.uid()) is null then
    return;
  end if;

  if normalized_event not in (
    'signup_completed',
    'scrim_posted',
    'extraction_completed',
    'extraction_failed'
  ) then
    return;
  end if;

  if normalized_status not in ('success', 'pending', 'failed', 'open') then
    normalized_status := 'success';
  end if;

  if event_metadata is not null and jsonb_typeof(event_metadata) = 'object' then
    safe_metadata := event_metadata;
  end if;

  insert into public.admin_activity_logs (
    actor_user_id,
    entity_type,
    entity_id,
    action,
    target_label,
    status,
    details,
    metadata
  ) values (
    (select auth.uid()),
    'analytics',
    entity_id,
    normalized_event,
    left(coalesce(nullif(target_label, ''), 'Launch analytics'), 120),
    normalized_status,
    left(coalesce(event_details, ''), 300),
    safe_metadata || jsonb_build_object('source', 'launch_analytics_rpc')
  );
end
$$;

revoke all on function public.track_matchmake_analytics_event(text, text, text, uuid, text, jsonb) from public, anon;
grant execute on function public.track_matchmake_analytics_event(text, text, text, uuid, text, jsonb) to authenticated;

drop trigger if exists users_admin_activity_after_write on public.users;
create trigger users_admin_activity_after_write
after insert or update or delete on public.users
for each row execute function private.capture_matchmake_activity();

drop trigger if exists organizations_admin_activity_after_write on public.organizations;
create trigger organizations_admin_activity_after_write
after insert or update or delete on public.organizations
for each row execute function private.capture_matchmake_activity();

drop trigger if exists teams_admin_activity_after_write on public.teams;
create trigger teams_admin_activity_after_write
after insert or update or delete on public.teams
for each row execute function private.capture_matchmake_activity();

drop trigger if exists scrim_requests_admin_activity_after_write on public.scrim_requests;
create trigger scrim_requests_admin_activity_after_write
after insert or update or delete on public.scrim_requests
for each row execute function private.capture_matchmake_activity();

drop trigger if exists scrim_messages_admin_activity_after_write on public.scrim_messages;
create trigger scrim_messages_admin_activity_after_write
after insert or update or delete on public.scrim_messages
for each row execute function private.capture_matchmake_activity();

drop trigger if exists team_match_reviews_admin_activity_after_write on public.team_match_reviews;
create trigger team_match_reviews_admin_activity_after_write
after insert or update or delete on public.team_match_reviews
for each row execute function private.capture_matchmake_activity();

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'admin_activity_logs'
  ) then
    alter publication supabase_realtime add table public.admin_activity_logs;
  end if;
end
$$;

grant select, insert, update, delete on table
  public.users,
  public.organizations,
  public.teams,
  public.scrim_requests,
  public.scrim_messages,
  public.team_match_reviews
to authenticated;

drop policy if exists "Matchmake owners can manage users" on public.users;
create policy "Matchmake owners can manage users"
  on public.users for all to authenticated
  using ((select private.is_matchmake_owner()))
  with check ((select private.is_matchmake_owner()));

drop policy if exists "Matchmake owners can manage organizations" on public.organizations;
create policy "Matchmake owners can manage organizations"
  on public.organizations for all to authenticated
  using ((select private.is_matchmake_owner()))
  with check ((select private.is_matchmake_owner()));

drop policy if exists "Matchmake owners can manage teams" on public.teams;
create policy "Matchmake owners can manage teams"
  on public.teams for all to authenticated
  using ((select private.is_matchmake_owner()))
  with check ((select private.is_matchmake_owner()));

drop policy if exists "Matchmake owners can manage scrims" on public.scrim_requests;
create policy "Matchmake owners can manage scrims"
  on public.scrim_requests for all to authenticated
  using ((select private.is_matchmake_owner()))
  with check ((select private.is_matchmake_owner()));

drop policy if exists "Matchmake owners can manage chat" on public.scrim_messages;
create policy "Matchmake owners can manage chat"
  on public.scrim_messages for all to authenticated
  using ((select private.is_matchmake_owner()))
  with check ((select private.is_matchmake_owner()));

drop policy if exists "Matchmake owners can manage match reviews" on public.team_match_reviews;
create policy "Matchmake owners can manage match reviews"
  on public.team_match_reviews for all to authenticated
  using ((select private.is_matchmake_owner()))
  with check ((select private.is_matchmake_owner()));

insert into public.admin_activity_logs (
  actor_user_id,
  entity_type,
  entity_id,
  action,
  target_label,
  status,
  details
)
select
  null,
  'system',
  null,
  'enabled audit logging',
  'Matchmake administration',
  'success',
  'Live owner activity logging is active'
where not exists (
  select 1
  from public.admin_activity_logs
  where entity_type = 'system'
    and action = 'enabled audit logging'
);

-- Seed the owner timeline with real recent records so the first dashboard load
-- has useful history. Future writes are captured by the triggers above.
insert into public.admin_activity_logs (
  actor_user_id,
  entity_type,
  entity_id,
  action,
  target_label,
  status,
  details,
  metadata,
  created_at
)
select
  auth_actor.id,
  event.entity_type,
  event.entity_id,
  event.action,
  event.target_label,
  event.status,
  event.details,
  jsonb_build_object('backfilled', true),
  event.created_at
from (
  select
    app_user.id as actor_user_id,
    'users'::text as entity_type,
    app_user.id as entity_id,
    'created user'::text as action,
    app_user.display_name as target_label,
    'success'::text as status,
    app_user.account_type as details,
    app_user.created_at
  from public.users app_user

  union all

  select
    organization.org_admin_id,
    'organizations',
    organization.id,
    'created organization',
    organization.name,
    case when organization.verified_flag then 'success' else 'pending' end,
    coalesce(organization.region, organization.type),
    organization.created_at
  from public.organizations organization

  union all

  select
    organization.org_admin_id,
    'teams',
    team.id,
    'created team',
    team.name,
    'success',
    team.game_title,
    team.created_at
  from public.teams team
  join public.organizations organization on organization.id = team.org_id

  union all

  select
    organization.org_admin_id,
    'scrim_requests',
    scrim.id,
    'created scrim',
    scrim.game_title || ' scrim',
    case when scrim.status in ('pending', 'matched', 'accepted') then 'pending' else 'success' end,
    'Status: ' || scrim.status,
    scrim.created_at
  from public.scrim_requests scrim
  join public.teams team on team.id = scrim.posting_team_id
  join public.organizations organization on organization.id = team.org_id

  union all

  select
    message.sender_user_id,
    'scrim_messages',
    message.id,
    'sent message',
    coalesce(message.sender_display_name, 'Participant') || ' in scrim chat',
    'success',
    'Conversation activity',
    message.created_at
  from public.scrim_messages message

  union all

  select
    review.created_by,
    'team_match_reviews',
    review.id,
    'submitted review',
    review.game_title || ' review',
    case when review.manual_edit_required then 'pending' else 'success' end,
    case when review.manual_edit_required then 'Manual review required' else coalesce(review.match_result, review.parser_status) end,
    review.created_at
  from public.team_match_reviews review
) event
left join auth.users auth_actor on auth_actor.id = event.actor_user_id
where not exists (
  select 1
  from public.admin_activity_logs existing
  where existing.entity_type = event.entity_type
    and existing.entity_id = event.entity_id
    and existing.action = event.action
    and existing.created_at = event.created_at
)
order by event.created_at desc
limit 250;
