-- Matchmake owner-only report queue.
-- Apply after database_schema.sql, scoped RLS files, and supabase_admin_dashboard.sql.

create extension if not exists "pgcrypto";

create table if not exists public.report_cases (
  id uuid primary key default gen_random_uuid(),
  case_number bigint generated by default as identity unique,
  title text not null check (char_length(btrim(title)) > 0),
  summary text,
  report_type text not null default 'general'
    check (report_type in ('chat', 'match_review', 'scrim', 'team', 'user', 'organization', 'support', 'safety', 'privacy', 'general')),
  severity integer not null default 2
    check (severity in (0, 1, 2)),
  status text not null default 'new'
    check (status in ('new', 'triage', 'waiting_on_school', 'waiting_on_matchmake', 'escalated', 'action_pending', 'verification_pending', 'monitoring', 'closed')),
  source text not null default 'owner_created',
  reporter_role text,
  organization_id uuid references public.organizations(id) on delete set null,
  team_id uuid references public.teams(id) on delete set null,
  scrim_request_id uuid references public.scrim_requests(id) on delete set null,
  scrim_message_id uuid references public.scrim_messages(id) on delete set null,
  match_review_id uuid references public.team_match_reviews(id) on delete set null,
  subject_user_id uuid references auth.users(id) on delete set null,
  assigned_owner_id uuid references auth.users(id) on delete set null,
  next_update_at timestamptz,
  closed_at timestamptz,
  resolution text,
  ai_triage_status text not null default 'not_requested'
    check (ai_triage_status in ('not_requested', 'queued', 'in_progress', 'suggested', 'accepted', 'rejected', 'blocked')),
  ai_triage_notes text,
  agent_context jsonb not null default '{}'::jsonb
    check (jsonb_typeof(agent_context) = 'object'),
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists report_cases_status_created_at_idx
  on public.report_cases(status, created_at desc);
create index if not exists report_cases_severity_status_idx
  on public.report_cases(severity, status, created_at desc);
create index if not exists report_cases_next_update_idx
  on public.report_cases(next_update_at)
  where status <> 'closed' and next_update_at is not null;
create index if not exists report_cases_org_team_idx
  on public.report_cases(organization_id, team_id, created_at desc);
create index if not exists report_cases_scrim_message_idx
  on public.report_cases(scrim_request_id, scrim_message_id, created_at desc);
create index if not exists report_cases_match_review_idx
  on public.report_cases(match_review_id, created_at desc);
create index if not exists report_cases_agent_context_gin_idx
  on public.report_cases using gin(agent_context);

alter table public.report_cases enable row level security;
revoke all on table public.report_cases from public, anon, authenticated;
grant select, insert, update, delete on table public.report_cases to authenticated;
grant usage, select on sequence public.report_cases_case_number_seq to authenticated;

drop policy if exists "Matchmake owners can manage report cases" on public.report_cases;
create policy "Matchmake owners can manage report cases"
  on public.report_cases for all to authenticated
  using ((select private.is_matchmake_owner()))
  with check ((select private.is_matchmake_owner()));

create or replace function private.capture_report_case_activity()
returns trigger
language plpgsql
security definer
set search_path = public, private, auth, pg_temp
as $$
declare
  row_data jsonb;
  old_data jsonb;
  activity_actor uuid;
  activity_action text;
  activity_target text;
  activity_status text := 'open';
  activity_details text;
begin
  row_data := case when tg_op = 'DELETE' then to_jsonb(old) else to_jsonb(new) end;
  old_data := case when tg_op = 'UPDATE' then to_jsonb(old) else '{}'::jsonb end;
  activity_actor := coalesce((select auth.uid()), nullif(row_data ->> 'created_by', '')::uuid);
  activity_target := 'MM-REPORT-' || lpad(coalesce(row_data ->> 'case_number', '0'), 4, '0');

  activity_action := case
    when tg_op = 'INSERT' then 'created report'
    when tg_op = 'UPDATE' then 'updated report'
    else 'removed report'
  end;

  if tg_op = 'UPDATE' and (old_data ->> 'status') is distinct from (row_data ->> 'status') then
    activity_details := coalesce(old_data ->> 'status', 'unknown') || ' to ' || coalesce(row_data ->> 'status', 'unknown');
  else
    activity_details := coalesce(row_data ->> 'title', 'Report case');
  end if;

  activity_status := case
    when row_data ->> 'status' = 'closed' then 'success'
    when row_data ->> 'status' in ('escalated', 'action_pending', 'verification_pending', 'triage', 'new') then 'pending'
    else 'open'
  end;

  insert into public.admin_activity_logs (
    actor_user_id,
    entity_type,
    entity_id,
    action,
    target_label,
    status,
    details,
    metadata
  ) values (
    activity_actor,
    'report_cases',
    nullif(row_data ->> 'id', '')::uuid,
    activity_action,
    activity_target,
    activity_status,
    activity_details,
    jsonb_build_object(
      'operation', tg_op,
      'report_type', row_data ->> 'report_type',
      'severity', row_data ->> 'severity',
      'source', row_data ->> 'source'
    )
  );

  return coalesce(new, old);
end
$$;

revoke all on function private.capture_report_case_activity() from public, anon, authenticated;

drop trigger if exists report_cases_admin_activity_after_write on public.report_cases;
create trigger report_cases_admin_activity_after_write
after insert or update or delete on public.report_cases
for each row execute function private.capture_report_case_activity();

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'report_cases'
  ) then
    alter publication supabase_realtime add table public.report_cases;
  end if;
end
$$;
