tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-dim": "#dad9df",
        "primary": "#0058bc",
        "surface-container-low": "#f4f3f8",
        "error": "#ba1a1a",
        "on-secondary": "#ffffff",
        "secondary-container": "#6664e4",
        "on-tertiary-fixed": "#351000",
        "error-container": "#ffdad6",
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#005bc1",
        "primary-fixed": "#d8e2ff",
        "inverse-on-surface": "#f1f0f5",
        "on-tertiary": "#ffffff",
        "on-surface-variant": "#414755",
        "surface-container-highest": "#e3e2e7",
        "secondary-fixed-dim": "#c2c1ff",
        "on-error-container": "#93000a",
        "on-surface": "#1a1b1f",
        "on-primary-fixed": "#001a41",
        "inverse-primary": "#adc6ff",
        "on-secondary-fixed": "#0c006a",
        "secondary": "#4c4aca",
        "surface-container": "#eeedf3",
        "secondary-fixed": "#e2dfff",
        "background": "#faf9fe",
        "surface-bright": "#faf9fe",
        "outline-variant": "#c1c6d7",
        "outline": "#717786",
        "on-primary": "#ffffff",
        "tertiary-fixed-dim": "#ffb595",
        "surface-variant": "#e3e2e7",
        "on-secondary-container": "#fffbff",
        "on-primary-container": "#fefcff",
        "tertiary-fixed": "#ffdbcc",
        "on-primary-fixed-variant": "#004493",
        "inverse-surface": "#2f3034",
        "primary-container": "#0070eb",
        "surface": "#faf9fe",
        "on-error": "#ffffff",
        "tertiary-container": "#c64f00",
        "primary-fixed-dim": "#adc6ff",
        "on-tertiary-fixed-variant": "#7c2e00",
        "on-background": "#1a1b1f",
        "tertiary": "#9e3d00",
        "surface-container-high": "#e9e7ed",
        "on-secondary-fixed-variant": "#3631b4",
        "on-tertiary-container": "#fffbff"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        md: "16px",
        xl: "32px",
        "margin-mobile": "20px",
        lg: "24px",
        gutter: "16px",
        sm: "8px",
        unit: "4px",
        xs: "4px"
      },
      fontFamily: {
        "label-small": ["Inter"],
        "headline-3": ["Inter"],
        "body-main": ["Inter"],
        "body-sub": ["Inter"],
        "headline-2": ["Inter"],
        "label-bold": ["Inter"],
        "headline-1": ["Inter"],
        "editorial-large": ["Inter"]
      },
      fontSize: {
        "label-small": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "headline-3": ["20px", { lineHeight: "25px", fontWeight: "600" }],
        "body-main": ["17px", { lineHeight: "22px", fontWeight: "400" }],
        "body-sub": ["15px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-2": ["22px", { lineHeight: "28px", fontWeight: "700" }],
        "label-bold": ["13px", { lineHeight: "18px", fontWeight: "600" }],
        "headline-1": ["28px", { lineHeight: "34px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "editorial-large": ["34px", { lineHeight: "41px", letterSpacing: "-0.02em", fontWeight: "800" }]
      }
    }
  }
};
